### ISSUE TITLE
OpenSettingsPlusAndroid.appNotification requires package name

### ISSUE THREAD

**Issue by FCView** [yanncabral/open_settings_plus#17]
Run the example on Android 14 and tap "Open app notification". You get a message "Unable to find application to perform action."

This is because the package needs to be included with the APP_NOTIFICATION_SETTINGS intent.

See here: https://developer.android.com/reference/android/provider/Settings#ACTION_APP_NOTIFICATION_SETTINGS

**Comment by FCView** [comment]
I uploaded a pull request (#18 ) to fix this.

**Comment by ValarDohaerisX** [comment]
I hope to merge the code soon, as I also need this feature

**Comment by yanncabral** [comment]
This issue has been fixed in version 0.4.0 which is now available on pub.dev.

The fix includes proper handling of the package name for `APP_NOTIFICATION_SETTINGS` intent across different Android versions, as specified in the [Android documentation](https://developer.android.com/reference/android/provider/Settings#ACTION_APP_NOTIFICATION_SETTINGS).

Thanks @FCView  for reporting and providing the PR with the fix! Let me know if you experience any other issues.
