### ISSUE TITLE
Android build warning

### ISSUE THREAD

**Issue by JaseElder** [yanncabral/open_settings_plus#19]
Getting the error:

`namespace and testNamespace have the same value ("br.com.yanncabral.open_settings_plus"), which is not allowed.`

Using gradle 8.7

**Comment by djesusguimaraes** [comment]
Getting the same, but like a warning, using Gradle 8.2.2:

![image](https://github.com/user-attachments/assets/d88d7730-b190-407f-86ce-0a4b288602a5)

**Comment by yanncabral** [comment]
This issue has been fixed in version 0.4.0 which is now available on pub.dev.

The fix includes changing the testNamespace to `br.com.yanncabral.open_settings_plus.test` to avoid the namespace conflict warning in Gradle 8.x.

Please let me know if you experience any other issues. Thanks for reporting!
